onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider DPIF
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/ihit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemload
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemaddr
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dhit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/datomic
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemWEN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/flushed
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemload
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemstore
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemaddr
add wave -noupdate -divider CCIF
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/CPUS
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/CPUID
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/iwait
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/dwait
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/iREN
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/dREN
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/dWEN
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/iload
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/dload
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/dstore
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/iaddr
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/daddr
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ccwait
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ccinv
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ccwrite
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/cctrans
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ccsnoopaddr
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ramWEN
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ramREN
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ramstate
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ramaddr
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ramstore
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ramload
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/iwait
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/iload
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/dwait
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/dload
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ccwait
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ccinv
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ccsnoopaddr
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/iREN
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/iaddr
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/dREN
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/dWEN
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/daddr
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/dstore
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/ccwrite
add wave -noupdate /system_tb/DUT/CPU/CM/ccif/cctrans
add wave -noupdate -divider DCACHE
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/CLK
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/nRST
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/curr_state
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_state
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/dcache_sel
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/block1_data1
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/block1_data2
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/block2_data1
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/block2_data2
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_block1_data1
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_block1_data2
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_block2_data1
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_block2_data2
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/block1_tag
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_block1_tag
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/block2_tag
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_block2_tag
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/block1_valid
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_block1_valid
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/block2_valid
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_block2_valid
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/block1_dirty
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_block1_dirty
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/block2_dirty
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_block2_dirty
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/recent_block
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/next_recent_block
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/hit
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/hit1
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/hit2
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/hit_counter
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/hit_counter_next
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/flush_idx_count
add wave -noupdate /system_tb/DUT/CPU/CM/DCACHE/flush_idx_count_next
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3278446312 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {3278362460 ps} {3280044082 ps}
