onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /system_tb/CLK
add wave -noupdate /system_tb/nRST
add wave -noupdate /system_tb/DUT/CPU/DP/PC_INIT
add wave -noupdate /system_tb/DUT/CPU/DP/CLK
add wave -noupdate /system_tb/DUT/CPU/DP/nRST
add wave -noupdate /system_tb/DUT/CPU/DP/rtype
add wave -noupdate /system_tb/DUT/CPU/DP/MtR_out
add wave -noupdate /system_tb/DUT/CPU/DP/ALUSrc_out
add wave -noupdate /system_tb/DUT/CPU/DP/Mux_lui
add wave -noupdate /system_tb/DUT/CPU/DP/Baddr
add wave -noupdate /system_tb/DUT/CPU/DP/RegDst_out
add wave -noupdate /system_tb/DUT/CPU/DP/npc
add wave -noupdate /system_tb/DUT/CPU/DP/jump_out
add wave -noupdate /system_tb/DUT/CPU/DP/branch_out
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/ihit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemload
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemaddr
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dhit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemWEN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/flushed
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemload
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemstore
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemaddr
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/opcode
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/funct
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/lui
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/jr
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/RegW
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/Branch
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/jump
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/Dwen
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/Dren
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/Iren
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ALUsource
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/BNE
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/regDest
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ExtSel
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/Mem
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/opcode_ALU
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/WEN
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/wsel
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rsel1
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rsel2
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/wdat
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rdat1
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rdat2
add wave -noupdate /system_tb/DUT/CPU/DP/alif/neg_flag
add wave -noupdate /system_tb/DUT/CPU/DP/alif/over_flag
add wave -noupdate /system_tb/DUT/CPU/DP/alif/zero_flag
add wave -noupdate /system_tb/DUT/CPU/DP/alif/portA
add wave -noupdate /system_tb/DUT/CPU/DP/alif/portB
add wave -noupdate /system_tb/DUT/CPU/DP/alif/outport
add wave -noupdate /system_tb/DUT/CPU/DP/alif/aluop
add wave -noupdate /system_tb/DUT/CPU/DP/pcif/PCen
add wave -noupdate /system_tb/DUT/CPU/DP/pcif/PCnext
add wave -noupdate /system_tb/DUT/CPU/DP/pcif/PCcurr
add wave -noupdate /system_tb/DUT/CPU/DP/eif/ExtSel
add wave -noupdate /system_tb/DUT/CPU/DP/eif/imm
add wave -noupdate /system_tb/DUT/CPU/DP/eif/extout
add wave -noupdate /system_tb/DUT/CPU/DP/ifid/npc_i
add wave -noupdate /system_tb/DUT/CPU/DP/ifid/npc_o
add wave -noupdate /system_tb/DUT/CPU/DP/ifid/iload_i
add wave -noupdate /system_tb/DUT/CPU/DP/ifid/iload_o
add wave -noupdate /system_tb/DUT/CPU/DP/ifid/iien
add wave -noupdate /system_tb/DUT/CPU/DP/ifid/flush
add wave -noupdate /system_tb/DUT/CPU/DP/idex/rdat2_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/rdat2_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/rdat1_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/rdat1_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/extout_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/extout_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/Jaddr_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/Jaddr_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/npc_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/npc_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/rs_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/rs_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/rd_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/rd_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/rt_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/rt_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/dload_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/dload_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/flush
add wave -noupdate /system_tb/DUT/CPU/DP/idex/lui_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/lui_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/jr_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/jr_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/RegW_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/RegW_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/Branch_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/Branch_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/jump_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/jump_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/DWen_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/DWen_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/DRen_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/DRen_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/ALUsource_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/ALUsource_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/BNE_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/BNE_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/halt_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/halt_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/Mem_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/Mem_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/RegDest_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/RegDest_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/ALUop_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/ALUop_o
add wave -noupdate /system_tb/DUT/CPU/DP/idex/opcode_i
add wave -noupdate /system_tb/DUT/CPU/DP/idex/opcode_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/rdat2_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/rdat2_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/rdat1_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/rdat1_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/extout_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/extout_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/Jaddr_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/Jaddr_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/npc_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/npc_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/alu_out_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/alu_out_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/rs_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/rs_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/rd_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/rd_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/rt_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/rt_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/dload_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/dload_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/enable
add wave -noupdate /system_tb/DUT/CPU/DP/exme/jr_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/jr_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/RegW_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/RegW_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/Branch_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/Branch_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/jump_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/jump_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/DWen_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/DWen_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/DRen_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/DRen_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/BNE_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/BNE_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/halt_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/halt_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/zero_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/zero_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/Mem_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/Mem_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/RegDest_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/RegDest_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/ALUop_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/ALUop_o
add wave -noupdate /system_tb/DUT/CPU/DP/exme/opcode_i
add wave -noupdate /system_tb/DUT/CPU/DP/exme/opcode_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/Addr_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/Addr_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/npc_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/npc_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/alu_out_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/alu_out_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/rs_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/rs_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/rd_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/rd_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/rt_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/rt_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/dload_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/dload_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/enable
add wave -noupdate /system_tb/DUT/CPU/DP/mem/RegW_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/RegW_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/halt_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/halt_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/Mem_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/Mem_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/RegDest_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/RegDest_o
add wave -noupdate /system_tb/DUT/CPU/DP/mem/opcode_i
add wave -noupdate /system_tb/DUT/CPU/DP/mem/opcode_o
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {250241 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {199899 ps} {435109 ps}
